name = "rooster"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzY2YjNmZmEtNGQ4NS00MGZhLWE1YjItYmJmMDJlNWEwNGI2IiwidGVuYW50X2lkIjoiOTk1NWUwMjQwZDE5OTM1ZTI2OWI4ZjQ5NWNjMzAzNWU3ZmVkYWIzMTQwYjNlM2E5N2M4OGIxYzZiMDQyZTA5NCIsImludGVybmFsX3NlY3JldCI6IjNjNTJlNDNmLTJjOTYtNDJhYS05NTdmLTg1NDFkZDFkNzQ1MiJ9.DsxbNgzZ593stJtsEdDzy_ylHxbLbDSjZ8CgpUd3tgI"
JWT_SECRET = "c7K$1p#Gq!zL@8sF2m*oH3vBwN5xU&9i"